[package]
name = "sdmx_json_de_tests"
description = "Testing JSON deserialization for sdmx_json crate"
publish = false
edition = "2021"

[dependencies]
sdmx_json.path = "../sdmx_json"
serde_json = "1.0.138"
